### ISSUE TITLE
Permission denied: Can't download!!

### ISSUE THREAD

**Issue by erikkonstas** [Zomis/Brainduck#50]

**Comment by Zomis** [comment]
Hi Erik. You should be able to get a release from here: https://github.com/Zomis/Brainduck/releases

Download the latest `*-all.jar` file and run it with `java -jar Brainduck-0.0.2-all.jar`

**Comment by Zomis** [comment]
I've also updated the README now. And I've started using my Jenkins for more automation. Right now the latest SNAPSHOT version can be found at http://stats.zomis.net:53654/job/brainduck/ws/build/libs/Brainduck-0.0.3-SNAPSHOT-all.jar
